-- Paginas legales (Terminos y Privacidad).
-- 1) Titulo en ingles: en /en/ el banner mostraba el titulo en espanol. El texto legal sigue solo en
--    espanol; tpl_page.php avisa en /en/ que el documento solo existe en espanol. Solo si esta vacio.
-- 2) Acentos que faltaban en el texto (Terminos, contratacion, politica...). Solo cambian acentos;
--    aplica unicamente si el texto sigue igual al que se corrigio.
SET NAMES utf8mb4;
UPDATE blocks SET value_en='Terms and conditions' WHERE page_id=(SELECT id FROM pages WHERE slug='terminos-y-condiciones') AND section='hero' AND skey='h1' AND (value_en IS NULL OR value_en='');
UPDATE blocks SET value_en='Privacy policy' WHERE page_id=(SELECT id FROM pages WHERE slug='politicas-de-privacidad') AND section='hero' AND skey='h1' AND (value_en IS NULL OR value_en='');
UPDATE blocks SET value_es='<section class="section"><div class="container prose reveal"><p>Los presentes Términos y Condiciones regulan el uso del sitio web de Aldea Networking y la contratación de nuestros espacios y servicios. Al utilizar este sitio aceptas las siguientes disposiciones.</p>
<h2>1. Información general</h2><p>Aldea Networking es una empresa 100% mexicana fundada en 2017, con domicilio en Aguascalientes, que opera espacios de trabajo en renta y coworking en el Bajío mexicano (León, San Luis Potosí, Aguascalientes y próximamente Querétaro).</p>
<h2>2. Servicios</h2><p>Ofrecemos oficinas privadas, coworking, domicilio virtual, escritorios privados y oficinas personalizadas. Las características, precios y disponibilidad pueden variar por ubicación y están sujetos a cambio sin previo aviso.</p>
<h2>3. Precios y contratación</h2><p>Los precios mostrados en el sitio son un punto de partida ("desde") y no incluyen IVA salvo que se indique. La contratación se formaliza mediante el contrato de prestación de servicios correspondiente.</p>
<h2>4. Uso del sitio</h2><p>El contenido, imágenes y marca de este sitio son propiedad de Aldea Networking. Queda prohibida su reproducción sin autorización. El sitio puede actualizarse en cualquier momento.</p>
<h2>5. Contacto</h2><p>Para cualquier duda escribe a <a href="mailto:contacto@aldea.work">contacto@aldea.work</a> o llama al +52 449 454 0709.</p><p style="font-size:.85rem;color:var(--muted);margin-top:2rem"><em>Documento en revisión. El texto legal definitivo será validado por el área jurídica de Aldea antes de la publicación final.</em></p></div></section>' WHERE page_id=(SELECT id FROM pages WHERE slug='terminos-y-condiciones') AND section='body' AND skey='body' AND value_es='<section class="section"><div class="container prose reveal"><p>Los presentes Terminos y Condiciones regulan el uso del sitio web de Aldea Networking y la contratacion de nuestros espacios y servicios. Al utilizar este sitio aceptas las siguientes disposiciones.</p>
<h2>1. Informacion general</h2><p>Aldea Networking es una empresa 100% mexicana fundada en 2017, con domicilio en Aguascalientes, que opera espacios de trabajo en renta y coworking en el Bajio mexicano (Leon, San Luis Potosi, Aguascalientes y proximamente Queretaro).</p>
<h2>2. Servicios</h2><p>Ofrecemos oficinas privadas, coworking, domicilio virtual, escritorios privados y oficinas personalizadas. Las caracteristicas, precios y disponibilidad pueden variar por ubicacion y estan sujetos a cambio sin previo aviso.</p>
<h2>3. Precios y contratacion</h2><p>Los precios mostrados en el sitio son un punto de partida ("desde") y no incluyen IVA salvo que se indique. La contratacion se formaliza mediante el contrato de prestacion de servicios correspondiente.</p>
<h2>4. Uso del sitio</h2><p>El contenido, imagenes y marca de este sitio son propiedad de Aldea Networking. Queda prohibida su reproduccion sin autorizacion. El sitio puede actualizarse en cualquier momento.</p>
<h2>5. Contacto</h2><p>Para cualquier duda escribe a <a href="mailto:contacto@aldea.work">contacto@aldea.work</a> o llama al +52 449 454 0709.</p><p style="font-size:.85rem;color:var(--muted);margin-top:2rem"><em>Documento en revision. El texto legal definitivo sera validado por el area juridica de Aldea antes de la publicacion final.</em></p></div></section>';
UPDATE blocks SET value_es='<section class="section"><div class="container prose reveal"><p>En Aldea Networking valoramos y protegemos tu privacidad. Esta política describe cómo recabamos, usamos y protegemos los datos personales que nos proporcionas a través de este sitio.</p>
<h2>1. Responsable</h2><p>Aldea Networking, empresa 100% mexicana con domicilio en Aguascalientes, México, es responsable del tratamiento de tus datos personales.</p>
<h2>2. Datos que recabamos</h2><p>Recabamos los datos que nos compartes al llenar nuestros formularios de contacto: nombre, correo electrónico, teléfono y el mensaje o solicitud que nos envías.</p>
<h2>3. Finalidad</h2><ul><li>Contactarte para dar seguimiento a tu solicitud de información o de tour.</li><li>Enviarte propuestas de espacios de trabajo acordes a tus necesidades.</li><li>Mejorar nuestros servicios y la experiencia en el sitio.</li></ul>
<h2>4. Protección de datos</h2><p>Implementamos medidas de seguridad administrativas, técnicas y físicas para proteger tus datos personales contra daño, pérdida o uso no autorizado.</p>
<h2>5. Derechos ARCO</h2><p>Puedes ejercer tus derechos de Acceso, Rectificación, Cancelación u Oposición, así como revocar tu consentimiento, escribiendo a <a href="mailto:contacto@aldea.work">contacto@aldea.work</a>.</p>
<h2>6. Contacto</h2><p>Para cualquier duda sobre esta política, escribe a <a href="mailto:contacto@aldea.work">contacto@aldea.work</a> o llama al +52 449 454 0709.</p><p style="font-size:.85rem;color:var(--muted);margin-top:2rem"><em>Documento en revisión. El texto legal definitivo será validado por el área jurídica de Aldea antes de la publicación final.</em></p></div></section>' WHERE page_id=(SELECT id FROM pages WHERE slug='politicas-de-privacidad') AND section='body' AND skey='body' AND value_es='<section class="section"><div class="container prose reveal"><p>En Aldea Networking valoramos y protegemos tu privacidad. Esta politica describe como recabamos, usamos y protegemos los datos personales que nos proporcionas a traves de este sitio.</p>
<h2>1. Responsable</h2><p>Aldea Networking, empresa 100% mexicana con domicilio en Aguascalientes, Mexico, es responsable del tratamiento de tus datos personales.</p>
<h2>2. Datos que recabamos</h2><p>Recabamos los datos que nos compartes al llenar nuestros formularios de contacto: nombre, correo electronico, telefono y el mensaje o solicitud que nos envias.</p>
<h2>3. Finalidad</h2><ul><li>Contactarte para dar seguimiento a tu solicitud de informacion o de tour.</li><li>Enviarte propuestas de espacios de trabajo acordes a tus necesidades.</li><li>Mejorar nuestros servicios y la experiencia en el sitio.</li></ul>
<h2>4. Proteccion de datos</h2><p>Implementamos medidas de seguridad administrativas, tecnicas y fisicas para proteger tus datos personales contra dano, perdida o uso no autorizado.</p>
<h2>5. Derechos ARCO</h2><p>Puedes ejercer tus derechos de Acceso, Rectificacion, Cancelacion u Oposicion, asi como revocar tu consentimiento, escribiendo a <a href="mailto:contacto@aldea.work">contacto@aldea.work</a>.</p>
<h2>6. Contacto</h2><p>Para cualquier duda sobre esta politica, escribe a <a href="mailto:contacto@aldea.work">contacto@aldea.work</a> o llama al +52 449 454 0709.</p><p style="font-size:.85rem;color:var(--muted);margin-top:2rem"><em>Documento en revision. El texto legal definitivo sera validado por el area juridica de Aldea antes de la publicacion final.</em></p></div></section>';
