-- =====================================================================
-- Rediseno 2026-09 (referencia de buenas practicas: wework.com)
-- Sedes: galerias con muchas mas fotos, cada una de su propia sede.
-- Las fotos salen del respaldo del WordPress viejo y de la carpeta del
-- cliente, identificadas por la pagina donde se usaban. Tamanos en /img/sedes/.
-- =====================================================================
SET NAMES utf8mb4;

UPDATE locations SET hero_image='/img/sedes/leon/coworking-cafe.webp', gallery='["/img/sedes/leon/coworking-cafe.webp","/img/sedes/leon/oficina-privada.webp","/img/sedes/leon/sala-de-juntas.webp","/img/sedes/leon/lounge.webp","/img/sedes/leon/reunion.webp","/img/sedes/leon/coworking.webp","/img/sedes/leon/escritorio-privado.webp","/img/sedes/leon/oficina-equipo.webp","/img/wp/2025/07/4-7.webp","/img/sedes/leon/recepcion.webp","/img/sedes/leon/sala-teal.webp","/img/sedes/leon/area-comun.webp","/img/sedes/leon/escritorio-miembro.webp","/img/sedes/leon/pasillo-plantas.webp","/img/loc-leon.webp","/img/wp/2025/07/8-7.webp","/img/wp/2025/07/2-7.webp","/img/wp/2025/07/9-7.webp"]' WHERE slug='oficinas-en-renta-leon-guanajuato';
UPDATE blocks SET value_es='/img/sedes/leon/oficina-equipo.webp' WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-leon-guanajuato') AND section='espacios' AND skey='p1_img';
UPDATE blocks SET value_es='/img/wp/2025/07/4-7.webp' WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-leon-guanajuato') AND section='espacios' AND skey='p2_img';
UPDATE blocks SET value_es='/img/sedes/leon/escritorio-privado.webp' WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-leon-guanajuato') AND section='espacios' AND skey='p3_img';
UPDATE blocks SET value_es='/img/sedes/leon/recepcion.webp' WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-leon-guanajuato') AND section='espacios' AND skey='p4_img';

UPDATE locations SET hero_image='/img/sedes/slp/lounge.webp', gallery='["/img/sedes/slp/lounge.webp","/img/sedes/slp/oficina-privada.webp","/img/sedes/slp/recepcion.webp","/img/sedes/slp/gradas.webp","/img/sedes/slp/reunion.webp","/img/sedes/slp/cabina.webp","/img/sedes/slp/coworking-panoramica.webp","/img/sedes/slp/lounge-plantas.webp","/img/sedes/slp/comunidad.webp","/img/sedes/slp/cocina.webp","/img/sedes/slp/trabajo.webp","/img/sedes/slp/area-trabajo.webp","/img/loc-slp.webp","/img/wp/2025/05/Espacios-de-trabajo-1-7-e1748535685261.webp","/img/wp/2025/05/Coworking-Space-1-5-e1748535585769.webp","/img/wp/2025/05/Oficina-privada-1-4.webp","/img/wp/2025/05/Sala-de-juntas-4.webp"]' WHERE slug='oficinas-en-renta-san-luis-potosi';
UPDATE blocks SET value_es='/img/wp/2025/05/Oficina-privada-1-4.webp' WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-san-luis-potosi') AND section='espacios' AND skey='p1_img';
UPDATE blocks SET value_es='/img/sedes/slp/coworking-panoramica.webp' WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-san-luis-potosi') AND section='espacios' AND skey='p2_img';
UPDATE blocks SET value_es='/img/sedes/slp/area-trabajo.webp' WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-san-luis-potosi') AND section='espacios' AND skey='p3_img';
UPDATE blocks SET value_es='/img/loc-slp.webp' WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-san-luis-potosi') AND section='espacios' AND skey='p4_img';

UPDATE locations SET hero_image='/img/sedes/ags/comunidad.webp', gallery='["/img/sedes/ags/comunidad.webp","/img/sedes/ags/coworking.webp","/img/sedes/ags/escritorios.webp","/img/sedes/ags/terraza.webp","/img/sedes/ags/sala-cobre.webp","/img/sedes/ags/lounge.webp","/img/sedes/ags/recepcion.webp","/img/sedes/ags/sala-geometrica.webp","/img/sedes/ags/sala-jungla.webp","/img/sedes/ags/escalera.webp","/img/sedes/ags/equipo.webp","/img/sedes/ags/area-comun.webp","/img/sedes/ags/edificio.webp","/img/loc-ags.webp","/img/wp/2025/06/Al-4-4.webp","/img/wp/2025/07/5-6-e1755036868866.webp","/img/wp/2025/06/Al-2-e1755036805656.webp","/img/wp/2025/07/1-6-e1755036822938.webp"]' WHERE slug='oficinas-en-renta-aguascalientes';
UPDATE blocks SET value_es='/img/wp/2025/07/1-6-e1755036822938.webp' WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-aguascalientes') AND section='espacios' AND skey='p2_img';
UPDATE blocks SET value_es='/img/sedes/ags/equipo.webp' WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-aguascalientes') AND section='espacios' AND skey='p3_img';
UPDATE blocks SET value_es='/img/sedes/ags/recepcion.webp' WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-aguascalientes') AND section='espacios' AND skey='p4_img';

UPDATE locations SET hero_image='/img/sedes/qro/lounge.webp', gallery='["/img/sedes/qro/lounge.webp","/img/wp/2026/05/Foto-oficina-qro-1.webp","/img/sedes/qro/cocina.webp","/img/wp/2026/05/Foto-oficina-qro-2.webp","/img/sedes/qro/recepcion.webp","/img/sedes/qro/torre.webp"]' WHERE slug='oficinas-en-renta-queretaro';
UPDATE blocks SET value_es='/img/wp/2026/05/Foto-oficina-qro-2.webp' WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-queretaro') AND section='espacios' AND skey='p1_img';
UPDATE blocks SET value_es='/img/sedes/qro/lounge.webp' WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-queretaro') AND section='espacios' AND skey='p2_img';
UPDATE blocks SET value_es='/img/wp/2026/05/Foto-oficina-qro-1.webp' WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-queretaro') AND section='espacios' AND skey='p3_img';
UPDATE blocks SET value_es='/img/sedes/qro/recepcion.webp' WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-queretaro') AND section='espacios' AND skey='p4_img';

-- Iconos que describen lo que dicen (condicionados a la etiqueta actual del campo).
UPDATE blocks SET value_es='parking' WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-san-luis-potosi') AND section='porque' AND skey='d2_icon' AND EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-san-luis-potosi') AND section='porque' AND skey='d2' AND value_es='Estacionamiento' LIMIT 1) t);
UPDATE blocks SET value_es='furniture' WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-san-luis-potosi') AND section='servicios' AND skey='s2_icon' AND EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-san-luis-potosi') AND section='servicios' AND skey='s2' AND value_es='Mobiliario' LIMIT 1) t);
UPDATE blocks SET value_es='presentation' WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-san-luis-potosi') AND section='servicios' AND skey='s3_icon' AND EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-san-luis-potosi') AND section='servicios' AND skey='s3' AND value_es='Salas de juntas' LIMIT 1) t);
UPDATE blocks SET value_es='desk' WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-san-luis-potosi') AND section='servicios' AND skey='s4_icon' AND EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-san-luis-potosi') AND section='servicios' AND skey='s4' AND value_es='Recepción' LIMIT 1) t);
UPDATE blocks SET value_es='spray' WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-san-luis-potosi') AND section='servicios' AND skey='s5_icon' AND EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-san-luis-potosi') AND section='servicios' AND skey='s5' AND value_es='Limpieza' LIMIT 1) t);
UPDATE blocks SET value_es='sofa' WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-san-luis-potosi') AND section='servicios' AND skey='s7_icon' AND EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-san-luis-potosi') AND section='servicios' AND skey='s7' AND value_es='Áreas comunes' LIMIT 1) t);
UPDATE blocks SET value_es='kitchen' WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-san-luis-potosi') AND section='servicios' AND skey='s9_icon' AND EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-san-luis-potosi') AND section='servicios' AND skey='s9' AND value_es='Cocina' LIMIT 1) t);
UPDATE blocks SET value_es='mailbox' WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-san-luis-potosi') AND section='servicios' AND skey='s10_icon' AND EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-san-luis-potosi') AND section='servicios' AND skey='s10' AND value_es='Paquetería' LIMIT 1) t);
UPDATE blocks SET value_es='parking' WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-queretaro') AND section='porque' AND skey='d2_icon' AND EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-queretaro') AND section='porque' AND skey='d2' AND value_es='Estacionamiento' LIMIT 1) t);
UPDATE blocks SET value_es='furniture' WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-queretaro') AND section='servicios' AND skey='s2_icon' AND EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-queretaro') AND section='servicios' AND skey='s2' AND value_es='Mobiliario' LIMIT 1) t);
UPDATE blocks SET value_es='presentation' WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-queretaro') AND section='servicios' AND skey='s3_icon' AND EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-queretaro') AND section='servicios' AND skey='s3' AND value_es='Salas de juntas' LIMIT 1) t);
UPDATE blocks SET value_es='desk' WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-queretaro') AND section='servicios' AND skey='s4_icon' AND EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-queretaro') AND section='servicios' AND skey='s4' AND value_es='Recepción' LIMIT 1) t);
UPDATE blocks SET value_es='spray' WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-queretaro') AND section='servicios' AND skey='s5_icon' AND EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-queretaro') AND section='servicios' AND skey='s5' AND value_es='Limpieza' LIMIT 1) t);
UPDATE blocks SET value_es='sofa' WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-queretaro') AND section='servicios' AND skey='s7_icon' AND EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-queretaro') AND section='servicios' AND skey='s7' AND value_es='Áreas comunes' LIMIT 1) t);
UPDATE blocks SET value_es='kitchen' WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-queretaro') AND section='servicios' AND skey='s9_icon' AND EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-queretaro') AND section='servicios' AND skey='s9' AND value_es='Cocina' LIMIT 1) t);
UPDATE blocks SET value_es='mailbox' WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-queretaro') AND section='servicios' AND skey='s10_icon' AND EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-queretaro') AND section='servicios' AND skey='s10' AND value_es='Paquetería' LIMIT 1) t);
UPDATE blocks SET value_es='pin' WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-leon-guanajuato') AND section='porque' AND skey='d1_icon' AND EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-leon-guanajuato') AND section='porque' AND skey='d1' AND value_es='Ubicación en Plaza Forum Center' LIMIT 1) t);
UPDATE blocks SET value_es='parking' WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-leon-guanajuato') AND section='porque' AND skey='d2_icon' AND EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-leon-guanajuato') AND section='porque' AND skey='d2' AND value_es='Estacionamiento' LIMIT 1) t);
UPDATE blocks SET value_es='route' WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-leon-guanajuato') AND section='porque' AND skey='d3_icon' AND EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-leon-guanajuato') AND section='porque' AND skey='d3' AND value_es='A 1.5 km de Poliforum León' LIMIT 1) t);
UPDATE blocks SET value_es='furniture' WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-leon-guanajuato') AND section='servicios' AND skey='s2_icon' AND EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-leon-guanajuato') AND section='servicios' AND skey='s2' AND value_es='Mobiliario' LIMIT 1) t);
UPDATE blocks SET value_es='presentation' WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-leon-guanajuato') AND section='servicios' AND skey='s3_icon' AND EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-leon-guanajuato') AND section='servicios' AND skey='s3' AND value_es='Salas de juntas' LIMIT 1) t);
UPDATE blocks SET value_es='desk' WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-leon-guanajuato') AND section='servicios' AND skey='s4_icon' AND EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-leon-guanajuato') AND section='servicios' AND skey='s4' AND value_es='Recepción' LIMIT 1) t);
UPDATE blocks SET value_es='spray' WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-leon-guanajuato') AND section='servicios' AND skey='s5_icon' AND EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-leon-guanajuato') AND section='servicios' AND skey='s5' AND value_es='Limpieza' LIMIT 1) t);
UPDATE blocks SET value_es='sofa' WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-leon-guanajuato') AND section='servicios' AND skey='s7_icon' AND EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-leon-guanajuato') AND section='servicios' AND skey='s7' AND value_es='Áreas comunes' LIMIT 1) t);
UPDATE blocks SET value_es='kitchen' WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-leon-guanajuato') AND section='servicios' AND skey='s9_icon' AND EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-leon-guanajuato') AND section='servicios' AND skey='s9' AND value_es='Cocina' LIMIT 1) t);
UPDATE blocks SET value_es='mailbox' WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-leon-guanajuato') AND section='servicios' AND skey='s10_icon' AND EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-leon-guanajuato') AND section='servicios' AND skey='s10' AND value_es='Paquetería' LIMIT 1) t);
UPDATE blocks SET value_es='pin' WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-aguascalientes') AND section='porque' AND skey='d1_icon' AND EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-aguascalientes') AND section='porque' AND skey='d1' AND value_es='Ubicación en Galerías Business Square' LIMIT 1) t);
UPDATE blocks SET value_es='parking' WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-aguascalientes') AND section='porque' AND skey='d2_icon' AND EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-aguascalientes') AND section='porque' AND skey='d2' AND value_es='Estacionamiento' LIMIT 1) t);
UPDATE blocks SET value_es='furniture' WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-aguascalientes') AND section='servicios' AND skey='s2_icon' AND EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-aguascalientes') AND section='servicios' AND skey='s2' AND value_es='Mobiliario' LIMIT 1) t);
UPDATE blocks SET value_es='presentation' WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-aguascalientes') AND section='servicios' AND skey='s3_icon' AND EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-aguascalientes') AND section='servicios' AND skey='s3' AND value_es='Salas de juntas' LIMIT 1) t);
UPDATE blocks SET value_es='desk' WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-aguascalientes') AND section='servicios' AND skey='s4_icon' AND EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-aguascalientes') AND section='servicios' AND skey='s4' AND value_es='Recepción' LIMIT 1) t);
UPDATE blocks SET value_es='spray' WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-aguascalientes') AND section='servicios' AND skey='s5_icon' AND EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-aguascalientes') AND section='servicios' AND skey='s5' AND value_es='Limpieza' LIMIT 1) t);
UPDATE blocks SET value_es='sofa' WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-aguascalientes') AND section='servicios' AND skey='s7_icon' AND EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-aguascalientes') AND section='servicios' AND skey='s7' AND value_es='Áreas comunes' LIMIT 1) t);
UPDATE blocks SET value_es='kitchen' WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-aguascalientes') AND section='servicios' AND skey='s9_icon' AND EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-aguascalientes') AND section='servicios' AND skey='s9' AND value_es='Cocina' LIMIT 1) t);
UPDATE blocks SET value_es='mailbox' WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-aguascalientes') AND section='servicios' AND skey='s10_icon' AND EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-aguascalientes') AND section='servicios' AND skey='s10' AND value_es='Paquetería' LIMIT 1) t);

-- Por que esta sede: se vacian las etiquetas que repiten el titulo o el parrafo de arriba.
UPDATE blocks SET value_es='', value_en='' WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-leon-guanajuato') AND section='porque' AND skey='d1' AND value_es='Ubicación en Plaza Forum Center';
UPDATE blocks SET value_es='', value_en='' WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-leon-guanajuato') AND section='porque' AND skey='d3' AND value_es='A 1.5 km de Poliforum León';
UPDATE blocks SET value_es='', value_en='' WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-san-luis-potosi') AND section='porque' AND skey='d1' AND value_es='Ubicación dentro de The Park';
UPDATE blocks SET value_es='', value_en='' WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-san-luis-potosi') AND section='porque' AND skey='d3' AND value_es='Conectividad con principales vialidades de San Luis Potosí';
UPDATE blocks SET value_es='', value_en='' WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-aguascalientes') AND section='porque' AND skey='d1' AND value_es='Ubicación en Galerías Business Square';
UPDATE blocks SET value_es='', value_en='' WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-aguascalientes') AND section='porque' AND skey='d3' AND value_es='Junto a C.C. Galerías y cerca de Altaria';
UPDATE blocks SET value_es='', value_en='' WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-queretaro') AND section='porque' AND skey='d1' AND value_es='Piso PH de Torre Capita Sur';
UPDATE blocks SET value_es='', value_en='' WHERE page_id=(SELECT id FROM pages WHERE slug='loc:oficinas-en-renta-queretaro') AND section='porque' AND skey='d3' AND value_es='Acceso desde los principales puntos de la ciudad';

-- La nota de Domicilio Virtual repetia lo que ya dice su descripcion.
UPDATE blocks SET value_es='', value_en='' WHERE page_id IN (SELECT id FROM (SELECT id FROM pages WHERE slug LIKE 'loc:%') t) AND section='espacios' AND skey='p4_nota';

-- =====================================================================
-- Oficinas Corporativas: comunicar que es una oficina completa, llave en
-- mano (inmueble, adecuacion, mobiliario, personalizacion y operacion),
-- no coworking. Galeria de un proyecto real en lugar de las imagenes IA.
-- =====================================================================
UPDATE blocks SET value_es='Tu oficina completa, llave en mano: elegimos el inmueble, lo adecuamos, lo amueblamos y lo operamos para tu empresa.', value_en='Your entire office, turnkey: we find the property, fit it out, furnish it and run it for your company.' WHERE page_id=(SELECT id FROM pages WHERE slug='oficinas-corporativas') AND section='hero' AND skey='lead';
-- La etiqueta sobre el titulo, el segundo parrafo y el plazo pasan al texto de la seccion siguiente.
UPDATE blocks SET value_es='', value_en='' WHERE page_id=(SELECT id FROM pages WHERE slug='oficinas-corporativas') AND section='hero' AND skey='chip';
UPDATE blocks SET value_es='', value_en='' WHERE page_id=(SELECT id FROM pages WHERE slug='oficinas-corporativas') AND section='hero' AND skey='lead2';
UPDATE blocks SET value_es='', value_en='' WHERE page_id=(SELECT id FROM pages WHERE slug='oficinas-corporativas') AND section='hero' AND skey='plazo';
UPDATE blocks SET value_es='/img/corporativas/proyecto/planta-abierta.webp' WHERE page_id=(SELECT id FROM pages WHERE slug='oficinas-corporativas') AND section='hero' AND skey='img';
-- Que es: cuatro ejes con foto (antes cinco ejes de texto y una foto).
UPDATE blocks SET value_es='No es coworking. Es tu propia oficina, construida desde cero.', value_en='Not coworking. Your own office, built from scratch.' WHERE page_id=(SELECT id FROM pages WHERE slug='oficinas-corporativas') AND section='operacion' AND skey='title';
UPDATE blocks SET value_es='Aldea desarrolla la oficina completa de tu empresa y la entrega lista para operar, con un solo equipo y un solo punto de contacto. Para equipos de más de 100 personas, con contratos desde 36 meses.', value_en='Aldea develops your company''s entire office and hands it over ready to operate, with one team and a single point of contact. For teams of more than 100 people, with terms from 36 months.' WHERE page_id=(SELECT id FROM pages WHERE slug='oficinas-corporativas') AND section='operacion' AND skey='text';
UPDATE blocks SET value_es='El inmueble adecuado', value_en='The right property' WHERE page_id=(SELECT id FROM pages WHERE slug='oficinas-corporativas') AND section='operacion' AND skey='e1_title';
UPDATE blocks SET value_es='Buscamos y evaluamos la propiedad que se ajusta a tu operación, dentro o fuera de una sede Aldea.', value_en='We search for and assess the property that fits your operation, inside or outside an Aldea location.' WHERE page_id=(SELECT id FROM pages WHERE slug='oficinas-corporativas') AND section='operacion' AND skey='e1_text';
INSERT INTO blocks (page_id,section,skey,type,label,value_es,value_en,href,sort) SELECT (SELECT id FROM pages WHERE slug='oficinas-corporativas'),'operacion','e1_img','image','Eje 1 - fotografia','/img/corporativas/inmueble.webp','','',17 FROM dual WHERE NOT EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='oficinas-corporativas') AND section='operacion' AND skey='e1_img' LIMIT 1) t);
UPDATE blocks SET value_es='Adecuación y obra', value_en='Fit-out and construction' WHERE page_id=(SELECT id FROM pages WHERE slug='oficinas-corporativas') AND section='operacion' AND skey='e2_title';
UPDATE blocks SET value_es='Diseñamos la distribución y adecuamos las instalaciones: arquitectura, obra, red y seguridad.', value_en='We design the layout and adapt the premises: architecture, construction, network and security.' WHERE page_id=(SELECT id FROM pages WHERE slug='oficinas-corporativas') AND section='operacion' AND skey='e2_text';
INSERT INTO blocks (page_id,section,skey,type,label,value_es,value_en,href,sort) SELECT (SELECT id FROM pages WHERE slug='oficinas-corporativas'),'operacion','e2_img','image','Eje 2 - fotografia','/img/corporativas/proyecto/salas-verdes.webp','','',20 FROM dual WHERE NOT EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='oficinas-corporativas') AND section='operacion' AND skey='e2_img' LIMIT 1) t);
UPDATE blocks SET value_es='Mobiliario y equipamiento', value_en='Furniture and equipment' WHERE page_id=(SELECT id FROM pages WHERE slug='oficinas-corporativas') AND section='operacion' AND skey='e3_title';
UPDATE blocks SET value_es='Equipamos cada área con el mobiliario, la tecnología y la infraestructura que requiere tu equipo.', value_en='We equip every area with the furniture, technology and infrastructure your team needs.' WHERE page_id=(SELECT id FROM pages WHERE slug='oficinas-corporativas') AND section='operacion' AND skey='e3_text';
INSERT INTO blocks (page_id,section,skey,type,label,value_es,value_en,href,sort) SELECT (SELECT id FROM pages WHERE slug='oficinas-corporativas'),'operacion','e3_img','image','Eje 3 - fotografia','/img/corporativas/proyecto/lockers-lounge.webp','','',23 FROM dual WHERE NOT EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='oficinas-corporativas') AND section='operacion' AND skey='e3_img' LIMIT 1) t);
UPDATE blocks SET value_es='Hecha para tu empresa', value_en='Built for your company' WHERE page_id=(SELECT id FROM pages WHERE slug='oficinas-corporativas') AND section='operacion' AND skey='e4_title';
UPDATE blocks SET value_es='Integramos tu identidad en el espacio y administramos los servicios del día a día para que tu equipo solo se ocupe de trabajar.', value_en='We bring your brand into the space and manage day-to-day services so your team can focus on work.' WHERE page_id=(SELECT id FROM pages WHERE slug='oficinas-corporativas') AND section='operacion' AND skey='e4_text';
INSERT INTO blocks (page_id,section,skey,type,label,value_es,value_en,href,sort) SELECT (SELECT id FROM pages WHERE slug='oficinas-corporativas'),'operacion','e4_img','image','Eje 4 - fotografia','/img/corporativas/corp-makeit.webp','','',26 FROM dual WHERE NOT EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='oficinas-corporativas') AND section='operacion' AND skey='e4_img' LIMIT 1) t);
-- El quinto eje (servicios) ya tiene su propia seccion.
UPDATE blocks SET value_es='', value_en='' WHERE page_id=(SELECT id FROM pages WHERE slug='oficinas-corporativas') AND section='operacion' AND skey='e5_title';
UPDATE blocks SET value_es='', value_en='' WHERE page_id=(SELECT id FROM pages WHERE slug='oficinas-corporativas') AND section='operacion' AND skey='e5_text';
-- Galeria del proyecto real. Las cuatro etapas generadas con IA y su nota se vacian;
-- los campos de etapas quedan en el panel por si llega material real del proceso.
UPDATE blocks SET value_es='Así se ve un proyecto terminado', value_en='What a finished project looks like' WHERE page_id=(SELECT id FROM pages WHERE slug='oficinas-corporativas') AND section='proyecto' AND skey='title';
UPDATE blocks SET value_es='Una oficina corporativa que Aldea desarrolló para un solo cliente: estaciones de trabajo, salas, cabinas, lockers y comedor.', value_en='A corporate office Aldea developed for a single client: workstations, meeting rooms, phone booths, lockers and a cafeteria.' WHERE page_id=(SELECT id FROM pages WHERE slug='oficinas-corporativas') AND section='proyecto' AND skey='text';
UPDATE blocks SET value_es='' WHERE page_id=(SELECT id FROM pages WHERE slug='oficinas-corporativas') AND section='proyecto' AND skey='e1_img';
UPDATE blocks SET value_es='' WHERE page_id=(SELECT id FROM pages WHERE slug='oficinas-corporativas') AND section='proyecto' AND skey='e2_img';
UPDATE blocks SET value_es='' WHERE page_id=(SELECT id FROM pages WHERE slug='oficinas-corporativas') AND section='proyecto' AND skey='e3_img';
UPDATE blocks SET value_es='' WHERE page_id=(SELECT id FROM pages WHERE slug='oficinas-corporativas') AND section='proyecto' AND skey='e4_img';
UPDATE blocks SET value_es='', value_en='' WHERE page_id=(SELECT id FROM pages WHERE slug='oficinas-corporativas') AND section='proyecto' AND skey='nota';
INSERT INTO blocks (page_id,section,skey,type,label,value_es,value_en,href,sort) SELECT (SELECT id FROM pages WHERE slug='oficinas-corporativas'),'proyecto','g1','image','Galeria - foto 1','/img/corporativas/proyecto/comedor-2.webp','','',111 FROM dual WHERE NOT EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='oficinas-corporativas') AND section='proyecto' AND skey='g1' LIMIT 1) t);
INSERT INTO blocks (page_id,section,skey,type,label,value_es,value_en,href,sort) SELECT (SELECT id FROM pages WHERE slug='oficinas-corporativas'),'proyecto','g2','image','Galeria - foto 2','/img/corporativas/proyecto/cabinas-y-salas.webp','','',112 FROM dual WHERE NOT EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='oficinas-corporativas') AND section='proyecto' AND skey='g2' LIMIT 1) t);
INSERT INTO blocks (page_id,section,skey,type,label,value_es,value_en,href,sort) SELECT (SELECT id FROM pages WHERE slug='oficinas-corporativas'),'proyecto','g3','image','Galeria - foto 3','/img/corporativas/proyecto/lockers-pasillo.webp','','',113 FROM dual WHERE NOT EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='oficinas-corporativas') AND section='proyecto' AND skey='g3' LIMIT 1) t);
INSERT INTO blocks (page_id,section,skey,type,label,value_es,value_en,href,sort) SELECT (SELECT id FROM pages WHERE slug='oficinas-corporativas'),'proyecto','g4','image','Galeria - foto 4','/img/corporativas/corp-openplan.webp','','',114 FROM dual WHERE NOT EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='oficinas-corporativas') AND section='proyecto' AND skey='g4' LIMIT 1) t);
INSERT INTO blocks (page_id,section,skey,type,label,value_es,value_en,href,sort) SELECT (SELECT id FROM pages WHERE slug='oficinas-corporativas'),'proyecto','g5','image','Galeria - foto 5','/img/corporativas/proyecto/lockers-lounge-2.webp','','',115 FROM dual WHERE NOT EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='oficinas-corporativas') AND section='proyecto' AND skey='g5' LIMIT 1) t);
INSERT INTO blocks (page_id,section,skey,type,label,value_es,value_en,href,sort) SELECT (SELECT id FROM pages WHERE slug='oficinas-corporativas'),'proyecto','g6','image','Galeria - foto 6','/img/corporativas/proyecto/comedor.webp','','',116 FROM dual WHERE NOT EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='oficinas-corporativas') AND section='proyecto' AND skey='g6' LIMIT 1) t);
INSERT INTO blocks (page_id,section,skey,type,label,value_es,value_en,href,sort) SELECT (SELECT id FROM pages WHERE slug='oficinas-corporativas'),'proyecto','g7','image','Galeria - foto 7','/img/corporativas/proyecto/planta-abierta.webp','','',117 FROM dual WHERE NOT EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='oficinas-corporativas') AND section='proyecto' AND skey='g7' LIMIT 1) t);
INSERT INTO blocks (page_id,section,skey,type,label,value_es,value_en,href,sort) SELECT (SELECT id FROM pages WHERE slug='oficinas-corporativas'),'proyecto','g8','image','Galeria - foto 8','/img/corporativas/proyecto/salas-verdes.webp','','',118 FROM dual WHERE NOT EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='oficinas-corporativas') AND section='proyecto' AND skey='g8' LIMIT 1) t);
INSERT INTO blocks (page_id,section,skey,type,label,value_es,value_en,href,sort) SELECT (SELECT id FROM pages WHERE slug='oficinas-corporativas'),'proyecto','g9','image','Galeria - foto 9','/img/corporativas/proyecto/lockers-lounge.webp','','',119 FROM dual WHERE NOT EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='oficinas-corporativas') AND section='proyecto' AND skey='g9' LIMIT 1) t);
INSERT INTO blocks (page_id,section,skey,type,label,value_es,value_en,href,sort) SELECT (SELECT id FROM pages WHERE slug='oficinas-corporativas'),'proyecto','g10','image','Galeria - foto 10','/img/corporativas/corp-makeit.webp','','',120 FROM dual WHERE NOT EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='oficinas-corporativas') AND section='proyecto' AND skey='g10' LIMIT 1) t);
INSERT INTO blocks (page_id,section,skey,type,label,value_es,value_en,href,sort) SELECT (SELECT id FROM pages WHERE slug='oficinas-corporativas'),'proyecto','g11','image','Galeria - foto 11','/img/corporativas/corp-panoramica.webp','','',121 FROM dual WHERE NOT EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='oficinas-corporativas') AND section='proyecto' AND skey='g11' LIMIT 1) t);
INSERT INTO blocks (page_id,section,skey,type,label,value_es,value_en,href,sort) SELECT (SELECT id FROM pages WHERE slug='oficinas-corporativas'),'proyecto','g12','image','Galeria - foto 12','/img/corporativas/corp-cabinas.webp','','',122 FROM dual WHERE NOT EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='oficinas-corporativas') AND section='proyecto' AND skey='g12' LIMIT 1) t);
-- Servicios: doce con icono (rejilla exacta de 4 x 3). El comodin 'Otros servicios' ya lo dice el texto.
UPDATE blocks SET value_es='', value_en='' WHERE page_id=(SELECT id FROM pages WHERE slug='oficinas-corporativas') AND section='servicios' AND skey='s13';
INSERT INTO blocks (page_id,section,skey,type,label,value_es,value_en,href,sort) SELECT (SELECT id FROM pages WHERE slug='oficinas-corporativas'),'servicios','s1_icon','text','Servicio 1 - icono','wifi','','',67 FROM dual WHERE NOT EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='oficinas-corporativas') AND section='servicios' AND skey='s1_icon' LIMIT 1) t);
INSERT INTO blocks (page_id,section,skey,type,label,value_es,value_en,href,sort) SELECT (SELECT id FROM pages WHERE slug='oficinas-corporativas'),'servicios','s2_icon','text','Servicio 2 - icono','desk','','',68 FROM dual WHERE NOT EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='oficinas-corporativas') AND section='servicios' AND skey='s2_icon' LIMIT 1) t);
INSERT INTO blocks (page_id,section,skey,type,label,value_es,value_en,href,sort) SELECT (SELECT id FROM pages WHERE slug='oficinas-corporativas'),'servicios','s3_icon','text','Servicio 3 - icono','spray','','',69 FROM dual WHERE NOT EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='oficinas-corporativas') AND section='servicios' AND skey='s3_icon' LIMIT 1) t);
INSERT INTO blocks (page_id,section,skey,type,label,value_es,value_en,href,sort) SELECT (SELECT id FROM pages WHERE slug='oficinas-corporativas'),'servicios','s4_icon','text','Servicio 4 - icono','shield','','',70 FROM dual WHERE NOT EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='oficinas-corporativas') AND section='servicios' AND skey='s4_icon' LIMIT 1) t);
INSERT INTO blocks (page_id,section,skey,type,label,value_es,value_en,href,sort) SELECT (SELECT id FROM pages WHERE slug='oficinas-corporativas'),'servicios','s5_icon','text','Servicio 5 - icono','fingerprint','','',71 FROM dual WHERE NOT EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='oficinas-corporativas') AND section='servicios' AND skey='s5_icon' LIMIT 1) t);
INSERT INTO blocks (page_id,section,skey,type,label,value_es,value_en,href,sort) SELECT (SELECT id FROM pages WHERE slug='oficinas-corporativas'),'servicios','s6_icon','text','Servicio 6 - icono','cctv','','',72 FROM dual WHERE NOT EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='oficinas-corporativas') AND section='servicios' AND skey='s6_icon' LIMIT 1) t);
INSERT INTO blocks (page_id,section,skey,type,label,value_es,value_en,href,sort) SELECT (SELECT id FROM pages WHERE slug='oficinas-corporativas'),'servicios','s7_icon','text','Servicio 7 - icono','tools','','',73 FROM dual WHERE NOT EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='oficinas-corporativas') AND section='servicios' AND skey='s7_icon' LIMIT 1) t);
INSERT INTO blocks (page_id,section,skey,type,label,value_es,value_en,href,sort) SELECT (SELECT id FROM pages WHERE slug='oficinas-corporativas'),'servicios','s8_icon','text','Servicio 8 - icono','support','','',74 FROM dual WHERE NOT EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='oficinas-corporativas') AND section='servicios' AND skey='s8_icon' LIMIT 1) t);
INSERT INTO blocks (page_id,section,skey,type,label,value_es,value_en,href,sort) SELECT (SELECT id FROM pages WHERE slug='oficinas-corporativas'),'servicios','s9_icon','text','Servicio 9 - icono','printer','','',75 FROM dual WHERE NOT EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='oficinas-corporativas') AND section='servicios' AND skey='s9_icon' LIMIT 1) t);
INSERT INTO blocks (page_id,section,skey,type,label,value_es,value_en,href,sort) SELECT (SELECT id FROM pages WHERE slug='oficinas-corporativas'),'servicios','s10_icon','text','Servicio 10 - icono','presentation','','',76 FROM dual WHERE NOT EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='oficinas-corporativas') AND section='servicios' AND skey='s10_icon' LIMIT 1) t);
INSERT INTO blocks (page_id,section,skey,type,label,value_es,value_en,href,sort) SELECT (SELECT id FROM pages WHERE slug='oficinas-corporativas'),'servicios','s11_icon','text','Servicio 11 - icono','parking','','',77 FROM dual WHERE NOT EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='oficinas-corporativas') AND section='servicios' AND skey='s11_icon' LIMIT 1) t);
INSERT INTO blocks (page_id,section,skey,type,label,value_es,value_en,href,sort) SELECT (SELECT id FROM pages WHERE slug='oficinas-corporativas'),'servicios','s12_icon','text','Servicio 12 - icono','kitchen','','',78 FROM dual WHERE NOT EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='oficinas-corporativas') AND section='servicios' AND skey='s12_icon' LIMIT 1) t);
-- Infraestructura: con foto; la nota al pie sobraba.
UPDATE blocks SET value_es='', value_en='' WHERE page_id=(SELECT id FROM pages WHERE slug='oficinas-corporativas') AND section='tech' AND skey='nota';
INSERT INTO blocks (page_id,section,skey,type,label,value_es,value_en,href,sort) SELECT (SELECT id FROM pages WHERE slug='oficinas-corporativas'),'tech','img','image','Fotografia','/img/corporativas/corp-panoramica.webp','','',81 FROM dual WHERE NOT EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='oficinas-corporativas') AND section='tech' AND skey='img' LIMIT 1) t);
-- Formulario con foto.
INSERT INTO blocks (page_id,section,skey,type,label,value_es,value_en,href,sort) SELECT (SELECT id FROM pages WHERE slug='oficinas-corporativas'),'form','img','image','Fotografia del formulario','/img/corporativas/corp-cabinas.webp','','',120 FROM dual WHERE NOT EXISTS (SELECT 1 FROM (SELECT 1 FROM blocks WHERE page_id=(SELECT id FROM pages WHERE slug='oficinas-corporativas') AND section='form' AND skey='img' LIMIT 1) t);
UPDATE pages SET seo_desc_es='Oficinas corporativas llave en mano para equipos de más de 100 personas: inmueble, adecuación, mobiliario, tecnología y servicios en una sola renta mensual.', seo_desc_en='Turnkey corporate offices for teams of more than 100 people: property, fit-out, furniture, technology and services in a single monthly rent.' WHERE slug='oficinas-corporativas';

-- =====================================================================
-- Espacios de trabajo: banners y galerias con mas fotos. Fuera la oficina
-- ensanchada con IA (op-4) y la fachada de Centro Sur en obra.
-- =====================================================================
UPDATE solutions SET hero_image='/img/sedes/leon/oficina-privada.webp', gallery='["/img/sedes/leon/oficina-privada.webp","/img/oficina-privada/op-1.webp","/img/sedes/leon/oficina-equipo.webp","/img/sedes/slp/oficina-privada.webp","/img/oficina-privada/op-2.webp","/img/espacios/oficina-equipo.webp","/img/oficina-privada/op-3.webp","/img/espacios/oficina-vacia.webp","/img/oficina-privada/op-5.webp","/img/espacios/oficina-laptop.webp","/img/oficina-privada/op-6.webp"]' WHERE slug='oficina-privada';
UPDATE solutions SET hero_image='/img/sedes/ags/coworking.webp', gallery='["/img/sedes/ags/coworking.webp","/img/sedes/leon/coworking.webp","/img/sedes/leon/coworking-cafe.webp","/img/sedes/slp/lounge.webp","/img/sedes/ags/comunidad.webp","/img/sedes/slp/cabina.webp","/img/sedes/leon/pasillo-plantas.webp","/img/wp/2025/07/11-1.webp","/img/wp/2025/07/1-2-e1756141254159.webp","/img/wp/2025/07/9-2.webp","/img/wp/2025/05/IMG_0093.webp","/img/wp/2025/07/2-2.webp","/img/wp/2025/07/10-2.webp"]' WHERE slug='coworking';
UPDATE solutions SET hero_image='/img/sedes/leon/escritorio-privado.webp', gallery='["/img/sedes/leon/escritorio-privado.webp","/img/sedes/ags/escritorios.webp","/img/sedes/leon/escritorio-miembro.webp","/img/sedes/ags/equipo.webp","/img/wp/2025/07/8-4.webp","/img/wp/2025/07/1-4.webp","/img/wp/2025/07/7-4.webp","/img/wp/2025/07/2-4.webp","/img/wp/2025/07/9-4.webp","/img/wp/2025/07/3-4.webp"]' WHERE slug='escritorio-privado';
UPDATE solutions SET hero_image='/img/sedes/ags/recepcion.webp', gallery='["/img/sedes/ags/recepcion.webp","/img/sedes/slp/recepcion.webp","/img/sedes/leon/recepcion.webp","/img/sedes/qro/recepcion.webp","/img/wp/2025/05/Sala-de-juntas-4.webp","/img/wp/2025/05/IMG_9553.webp","/img/sol-virtual.webp","/img/loc-qro.webp"]' WHERE slug='domicilio-virtual';

-- Banners de las paginas generales (antes una foto recortada junto al titulo).
UPDATE blocks SET value_es='/img/sedes/leon/recepcion.webp' WHERE page_id=(SELECT id FROM pages WHERE slug='contacto') AND section='hero' AND skey='hero_img';
UPDATE blocks SET value_es='/img/sedes/leon/lounge.webp' WHERE page_id=(SELECT id FROM pages WHERE slug='preguntas-frecuentes') AND section='hero' AND skey='hero_img';

-- Inicio: fotos del carrusel del banner, una por sede.
UPDATE blocks SET value_es='/img/sedes/slp/lounge.webp' WHERE page_id=(SELECT id FROM pages WHERE slug='') AND section='hero' AND skey='photo_a';
UPDATE blocks SET value_es='/img/sedes/leon/coworking-cafe.webp' WHERE page_id=(SELECT id FROM pages WHERE slug='') AND section='hero' AND skey='photo_b';
UPDATE blocks SET value_es='/img/sedes/ags/comunidad.webp' WHERE page_id=(SELECT id FROM pages WHERE slug='') AND section='hero' AND skey='photo_c';
UPDATE blocks SET value_es='/img/sedes/qro/lounge.webp' WHERE page_id=(SELECT id FROM pages WHERE slug='') AND section='hero' AND skey='photo_d';

-- Botones del Inicio: la flecha la dibuja el icono, no el texto.
UPDATE blocks SET value_es=TRIM(REPLACE(value_es,'→','')), value_en=TRIM(REPLACE(value_en,'→','')) WHERE page_id=(SELECT id FROM pages WHERE slug='') AND skey='cta' AND section IN ('corporativas','numeros');

-- =====================================================================
-- Acentos que faltaban en Contacto, Preguntas frecuentes y legales.
-- =====================================================================
UPDATE blocks SET value_es='Hablemos sobre tu próximo espacio de trabajo' WHERE page_id=(SELECT id FROM pages WHERE slug='contacto') AND section='hero' AND skey='h1';
UPDATE blocks SET value_es='Déjanos tus datos y un asesor se pondrá en contacto para entender lo que necesitas.' WHERE page_id=(SELECT id FROM pages WHERE slug='contacto') AND section='hero' AND skey='lead';
UPDATE blocks SET value_es='Escríbenos' WHERE page_id=(SELECT id FROM pages WHERE slug='contacto') AND section='body' AND skey='write_titulo';
UPDATE blocks SET value_es='Resolvemos las dudas más comunes sobre oficinas en renta y coworking en Aldea.' WHERE page_id=(SELECT id FROM pages WHERE slug='preguntas-frecuentes') AND section='hero' AND skey='lead';
UPDATE blocks SET value_es='¿Qué incluye la renta de una oficina en Aldea?' WHERE page_id=(SELECT id FROM pages WHERE slug='preguntas-frecuentes') AND section='body' AND skey='faq1_title';
UPDATE blocks SET value_es='¿Las oficinas cuentan con estacionamiento?' WHERE page_id=(SELECT id FROM pages WHERE slug='preguntas-frecuentes') AND section='body' AND skey='faq2_title';
UPDATE blocks SET value_es='¿Ofrecen oficinas amuebladas?' WHERE page_id=(SELECT id FROM pages WHERE slug='preguntas-frecuentes') AND section='body' AND skey='faq3_title';
UPDATE blocks SET value_es='¿Es posible expandir mi espacio si mi empresa crece?' WHERE page_id=(SELECT id FROM pages WHERE slug='preguntas-frecuentes') AND section='body' AND skey='faq4_title';
UPDATE blocks SET value_es='¿En qué ciudades tiene presencia Aldea?' WHERE page_id=(SELECT id FROM pages WHERE slug='preguntas-frecuentes') AND section='body' AND skey='faq5_title';
UPDATE blocks SET value_es='Todas nuestras soluciones son todo incluido: internet de alta velocidad, salas de juntas, café, impresiones, cocina, recepción, paquetería, limpieza, seguridad y áreas comunes, sin costos ocultos.' WHERE page_id=(SELECT id FROM pages WHERE slug='preguntas-frecuentes') AND section='body' AND skey='faq1_text';
UPDATE blocks SET value_es='Sí, disponemos de estacionamiento privado para inquilinos y espacios para visitantes en todas nuestras sedes.' WHERE page_id=(SELECT id FROM pages WHERE slug='preguntas-frecuentes') AND section='body' AND skey='faq2_text';
UPDATE blocks SET value_es='Sí, todas nuestras oficinas están completamente amuebladas con mobiliario ergonómico: escritorios ajustables, sillas ejecutivas, archiveros y más.' WHERE page_id=(SELECT id FROM pages WHERE slug='preguntas-frecuentes') AND section='body' AND skey='faq3_text';
UPDATE blocks SET value_es='Absolutamente. Nuestro modelo flexible permite escalar tu espacio según tus necesidades, con prioridad de expansión para inquilinos actuales.' WHERE page_id=(SELECT id FROM pages WHERE slug='preguntas-frecuentes') AND section='body' AND skey='faq4_text';
UPDATE blocks SET value_es='Términos y condiciones' WHERE page_id=(SELECT id FROM pages WHERE slug='terminos-y-condiciones') AND section='hero' AND skey='h1';
UPDATE pages SET title_es='Términos y condiciones' WHERE slug='terminos-y-condiciones';
UPDATE blocks SET value_es='Políticas de privacidad' WHERE page_id=(SELECT id FROM pages WHERE slug='politicas-de-privacidad') AND section='hero' AND skey='h1';
UPDATE pages SET title_es='Políticas de privacidad' WHERE slug='politicas-de-privacidad';

-- Cifras: el mismo orden y las mismas etiquetas en Inicio y Acerca de Aldea. En Acerca,
-- 'm²' pasa a la etiqueta (junto al numero se salia de su columna). Solo si no se han editado.
UPDATE blocks SET value_es='Año de fundación', value_en='Founded' WHERE page_id=(SELECT id FROM pages WHERE slug='') AND section='numeros' AND skey='n2_label' AND value_es='Desde';
UPDATE blocks SET value_es='4', value_en='4' WHERE page_id=(SELECT id FROM pages WHERE slug='acerca-de-aldea') AND section='numeros' AND skey='stat1_title' AND value_es='2017';
UPDATE blocks SET value_es='Ciudades', value_en='Cities' WHERE page_id=(SELECT id FROM pages WHERE slug='acerca-de-aldea') AND section='numeros' AND skey='stat1_text' AND value_es='Año de fundación';
UPDATE blocks SET value_es='2017', value_en='2017' WHERE page_id=(SELECT id FROM pages WHERE slug='acerca-de-aldea') AND section='numeros' AND skey='stat2_title' AND value_es='4';
UPDATE blocks SET value_es='Año de fundación', value_en='Founded' WHERE page_id=(SELECT id FROM pages WHERE slug='acerca-de-aldea') AND section='numeros' AND skey='stat2_text' AND value_es='Ciudades';
UPDATE blocks SET value_es='+6,000', value_en='+6,000' WHERE page_id=(SELECT id FROM pages WHERE slug='acerca-de-aldea') AND section='numeros' AND skey='stat5_title' AND value_es='+6,000 m²';
UPDATE blocks SET value_es='m² de espacio', value_en='sq m of space' WHERE page_id=(SELECT id FROM pages WHERE slug='acerca-de-aldea') AND section='numeros' AND skey='stat5_text' AND value_es='Espacios administrados';

-- Soluciones: las tarjetas Privado / Compartido repetian el parrafo de arriba casi palabra por
-- palabra. Se vacian en Oficina Privada, Coworking y Escritorio Privado (Domicilio Virtual se queda:
-- ahi son listas de lo que tienes y lo que no necesitas). Solo si no se han editado.
UPDATE blocks SET value_es='', value_en='' WHERE page_id=(SELECT id FROM pages WHERE slug='sol:oficina-privada') AND section='quees' AND skey='priv_title' AND value_es='Privado';
UPDATE blocks SET value_es='', value_en='' WHERE page_id=(SELECT id FROM pages WHERE slug='sol:oficina-privada') AND section='quees' AND skey='priv_text' AND value_es='Tu oficina y estaciones de trabajo.';
UPDATE blocks SET value_es='', value_en='' WHERE page_id=(SELECT id FROM pages WHERE slug='sol:oficina-privada') AND section='quees' AND skey='shared_title' AND value_es='Compartido';
UPDATE blocks SET value_es='', value_en='' WHERE page_id=(SELECT id FROM pages WHERE slug='sol:oficina-privada') AND section='quees' AND skey='shared_text' AND value_es='Recepción, salas de juntas, cocina y áreas comunes.';
UPDATE blocks SET value_es='', value_en='' WHERE page_id=(SELECT id FROM pages WHERE slug='sol:coworking') AND section='quees' AND skey='priv_title' AND value_es='Tu espacio de trabajo';
UPDATE blocks SET value_es='', value_en='' WHERE page_id=(SELECT id FROM pages WHERE slug='sol:coworking') AND section='quees' AND skey='priv_text' AND value_es='Eliges un lugar disponible dentro del área Coworking.';
UPDATE blocks SET value_es='', value_en='' WHERE page_id=(SELECT id FROM pages WHERE slug='sol:coworking') AND section='quees' AND skey='shared_title' AND value_es='Espacios compartidos';
UPDATE blocks SET value_es='', value_en='' WHERE page_id=(SELECT id FROM pages WHERE slug='sol:coworking') AND section='quees' AND skey='shared_text' AND value_es='Salas de juntas, cocina, recepción y áreas comunes.';
UPDATE blocks SET value_es='', value_en='' WHERE page_id=(SELECT id FROM pages WHERE slug='sol:escritorio-privado') AND section='quees' AND skey='priv_title' AND value_es='Exclusivo';
UPDATE blocks SET value_es='', value_en='' WHERE page_id=(SELECT id FROM pages WHERE slug='sol:escritorio-privado') AND section='quees' AND skey='priv_text' AND value_es='Tu escritorio y estación de trabajo están asignados únicamente para ti.';
UPDATE blocks SET value_es='', value_en='' WHERE page_id=(SELECT id FROM pages WHERE slug='sol:escritorio-privado') AND section='quees' AND skey='shared_title' AND value_es='Compartido';
UPDATE blocks SET value_es='', value_en='' WHERE page_id=(SELECT id FROM pages WHERE slug='sol:escritorio-privado') AND section='quees' AND skey='shared_text' AND value_es='La zona donde se encuentra tu escritorio, recepción, salas de juntas, cocina y áreas comunes.';

-- Blog: once articulos no tenian portada. Fotos de Aldea segun el tema de cada uno.
UPDATE posts SET cover_image='/img/sedes/leon/coworking.webp' WHERE slug='ventajas-de-elegir-un-coworking-en-leon-frente-a-una-oficina-tradicional' AND (cover_image IS NULL OR cover_image='');
UPDATE posts SET cover_image='/img/sedes/slp/reunion.webp' WHERE slug='como-vender-mas-desde-tu-espacio-de-trabajo-la-ventaja-invisible-del-coworking' AND (cover_image IS NULL OR cover_image='');
UPDATE posts SET cover_image='/img/sedes/ags/coworking.webp' WHERE slug='innovacion-empresarial-en-2025-por-que-el-espacio-de-trabajo-define-el-crecimiento' AND (cover_image IS NULL OR cover_image='');
UPDATE posts SET cover_image='/img/sedes/slp/oficina-privada.webp' WHERE slug='guia-para-elegir-el-espacio-de-trabajo-ideal-para-tu-empresa-en-2025' AND (cover_image IS NULL OR cover_image='');
UPDATE posts SET cover_image='/img/sedes/leon/sala-de-juntas.webp' WHERE slug='diseno-de-oficinas-que-inspiran-claves-para-tu-espacio-de-trabajo' AND (cover_image IS NULL OR cover_image='');
UPDATE posts SET cover_image='/img/sedes/slp/lounge.webp' WHERE slug='tendencias-2026-para-espacios-de-trabajo-flexibles-en-mexico' AND (cover_image IS NULL OR cover_image='');
UPDATE posts SET cover_image='/img/sedes/leon/oficina-privada.webp' WHERE slug='como-elegir-oficinas-en-renta-flexibles-en-el-bajio' AND (cover_image IS NULL OR cover_image='');
UPDATE posts SET cover_image='/img/sedes/ags/comunidad.webp' WHERE slug='entorno-colaborativo' AND (cover_image IS NULL OR cover_image='');
UPDATE posts SET cover_image='/img/sedes/slp/cabina.webp' WHERE slug='nomada-mexico' AND (cover_image IS NULL OR cover_image='');
UPDATE posts SET cover_image='/img/sedes/leon/coworking-cafe.webp' WHERE slug='coworking-mexico' AND (cover_image IS NULL OR cover_image='');
UPDATE posts SET cover_image='/img/sedes/qro/lounge.webp' WHERE slug='coworkings-queretaro' AND (cover_image IS NULL OR cover_image='');
