-- =====================================================================
-- ALDEA — traer al sitio nuevo las imagenes que aun vivian en el
-- WordPress viejo (aldea.work/wp-content/uploads/...).
-- Los archivos ya se copiaron a /img/wp/ espejando la ruta original,
-- por eso basta con reemplazar el prefijo.
--
-- Sin esto, el dia del cambio de dominio esas imagenes desaparecen.
-- =====================================================================

SET NAMES utf8mb4;

-- solutions
UPDATE `solutions` SET `hero_image`=REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(`hero_image`,'https://aldea.work/wp-content/uploads/','/img/wp/'),'https://www.aldea.work/wp-content/uploads/','/img/wp/'),'http://aldea.work/wp-content/uploads/','/img/wp/'),'http://www.aldea.work/wp-content/uploads/','/img/wp/'),'https:\\/\\/aldea.work\\/wp-content\\/uploads\\/','\\/img\\/wp\\/'),'https:\\/\\/www.aldea.work\\/wp-content\\/uploads\\/','\\/img\\/wp\\/') WHERE `hero_image` LIKE '%wp-content%';
UPDATE `solutions` SET `gallery`=REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(`gallery`,'https://aldea.work/wp-content/uploads/','/img/wp/'),'https://www.aldea.work/wp-content/uploads/','/img/wp/'),'http://aldea.work/wp-content/uploads/','/img/wp/'),'http://www.aldea.work/wp-content/uploads/','/img/wp/'),'https:\\/\\/aldea.work\\/wp-content\\/uploads\\/','\\/img\\/wp\\/'),'https:\\/\\/www.aldea.work\\/wp-content\\/uploads\\/','\\/img\\/wp\\/') WHERE `gallery` LIKE '%wp-content%';
UPDATE `solutions` SET `body_es`=REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(`body_es`,'https://aldea.work/wp-content/uploads/','/img/wp/'),'https://www.aldea.work/wp-content/uploads/','/img/wp/'),'http://aldea.work/wp-content/uploads/','/img/wp/'),'http://www.aldea.work/wp-content/uploads/','/img/wp/'),'https:\\/\\/aldea.work\\/wp-content\\/uploads\\/','\\/img\\/wp\\/'),'https:\\/\\/www.aldea.work\\/wp-content\\/uploads\\/','\\/img\\/wp\\/') WHERE `body_es` LIKE '%wp-content%';
UPDATE `solutions` SET `body_en`=REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(`body_en`,'https://aldea.work/wp-content/uploads/','/img/wp/'),'https://www.aldea.work/wp-content/uploads/','/img/wp/'),'http://aldea.work/wp-content/uploads/','/img/wp/'),'http://www.aldea.work/wp-content/uploads/','/img/wp/'),'https:\\/\\/aldea.work\\/wp-content\\/uploads\\/','\\/img\\/wp\\/'),'https:\\/\\/www.aldea.work\\/wp-content\\/uploads\\/','\\/img\\/wp\\/') WHERE `body_en` LIKE '%wp-content%';

-- locations
UPDATE `locations` SET `hero_image`=REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(`hero_image`,'https://aldea.work/wp-content/uploads/','/img/wp/'),'https://www.aldea.work/wp-content/uploads/','/img/wp/'),'http://aldea.work/wp-content/uploads/','/img/wp/'),'http://www.aldea.work/wp-content/uploads/','/img/wp/'),'https:\\/\\/aldea.work\\/wp-content\\/uploads\\/','\\/img\\/wp\\/'),'https:\\/\\/www.aldea.work\\/wp-content\\/uploads\\/','\\/img\\/wp\\/') WHERE `hero_image` LIKE '%wp-content%';
UPDATE `locations` SET `gallery`=REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(`gallery`,'https://aldea.work/wp-content/uploads/','/img/wp/'),'https://www.aldea.work/wp-content/uploads/','/img/wp/'),'http://aldea.work/wp-content/uploads/','/img/wp/'),'http://www.aldea.work/wp-content/uploads/','/img/wp/'),'https:\\/\\/aldea.work\\/wp-content\\/uploads\\/','\\/img\\/wp\\/'),'https:\\/\\/www.aldea.work\\/wp-content\\/uploads\\/','\\/img\\/wp\\/') WHERE `gallery` LIKE '%wp-content%';
UPDATE `locations` SET `intro_es`=REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(`intro_es`,'https://aldea.work/wp-content/uploads/','/img/wp/'),'https://www.aldea.work/wp-content/uploads/','/img/wp/'),'http://aldea.work/wp-content/uploads/','/img/wp/'),'http://www.aldea.work/wp-content/uploads/','/img/wp/'),'https:\\/\\/aldea.work\\/wp-content\\/uploads\\/','\\/img\\/wp\\/'),'https:\\/\\/www.aldea.work\\/wp-content\\/uploads\\/','\\/img\\/wp\\/') WHERE `intro_es` LIKE '%wp-content%';
UPDATE `locations` SET `intro_en`=REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(`intro_en`,'https://aldea.work/wp-content/uploads/','/img/wp/'),'https://www.aldea.work/wp-content/uploads/','/img/wp/'),'http://aldea.work/wp-content/uploads/','/img/wp/'),'http://www.aldea.work/wp-content/uploads/','/img/wp/'),'https:\\/\\/aldea.work\\/wp-content\\/uploads\\/','\\/img\\/wp\\/'),'https:\\/\\/www.aldea.work\\/wp-content\\/uploads\\/','\\/img\\/wp\\/') WHERE `intro_en` LIKE '%wp-content%';

-- posts
UPDATE `posts` SET `cover_image`=REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(`cover_image`,'https://aldea.work/wp-content/uploads/','/img/wp/'),'https://www.aldea.work/wp-content/uploads/','/img/wp/'),'http://aldea.work/wp-content/uploads/','/img/wp/'),'http://www.aldea.work/wp-content/uploads/','/img/wp/'),'https:\\/\\/aldea.work\\/wp-content\\/uploads\\/','\\/img\\/wp\\/'),'https:\\/\\/www.aldea.work\\/wp-content\\/uploads\\/','\\/img\\/wp\\/') WHERE `cover_image` LIKE '%wp-content%';
UPDATE `posts` SET `body_es`=REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(`body_es`,'https://aldea.work/wp-content/uploads/','/img/wp/'),'https://www.aldea.work/wp-content/uploads/','/img/wp/'),'http://aldea.work/wp-content/uploads/','/img/wp/'),'http://www.aldea.work/wp-content/uploads/','/img/wp/'),'https:\\/\\/aldea.work\\/wp-content\\/uploads\\/','\\/img\\/wp\\/'),'https:\\/\\/www.aldea.work\\/wp-content\\/uploads\\/','\\/img\\/wp\\/') WHERE `body_es` LIKE '%wp-content%';
UPDATE `posts` SET `body_en`=REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(`body_en`,'https://aldea.work/wp-content/uploads/','/img/wp/'),'https://www.aldea.work/wp-content/uploads/','/img/wp/'),'http://aldea.work/wp-content/uploads/','/img/wp/'),'http://www.aldea.work/wp-content/uploads/','/img/wp/'),'https:\\/\\/aldea.work\\/wp-content\\/uploads\\/','\\/img\\/wp\\/'),'https:\\/\\/www.aldea.work\\/wp-content\\/uploads\\/','\\/img\\/wp\\/') WHERE `body_en` LIKE '%wp-content%';
UPDATE `posts` SET `excerpt_es`=REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(`excerpt_es`,'https://aldea.work/wp-content/uploads/','/img/wp/'),'https://www.aldea.work/wp-content/uploads/','/img/wp/'),'http://aldea.work/wp-content/uploads/','/img/wp/'),'http://www.aldea.work/wp-content/uploads/','/img/wp/'),'https:\\/\\/aldea.work\\/wp-content\\/uploads\\/','\\/img\\/wp\\/'),'https:\\/\\/www.aldea.work\\/wp-content\\/uploads\\/','\\/img\\/wp\\/') WHERE `excerpt_es` LIKE '%wp-content%';
UPDATE `posts` SET `excerpt_en`=REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(`excerpt_en`,'https://aldea.work/wp-content/uploads/','/img/wp/'),'https://www.aldea.work/wp-content/uploads/','/img/wp/'),'http://aldea.work/wp-content/uploads/','/img/wp/'),'http://www.aldea.work/wp-content/uploads/','/img/wp/'),'https:\\/\\/aldea.work\\/wp-content\\/uploads\\/','\\/img\\/wp\\/'),'https:\\/\\/www.aldea.work\\/wp-content\\/uploads\\/','\\/img\\/wp\\/') WHERE `excerpt_en` LIKE '%wp-content%';

-- testimonials
UPDATE `testimonials` SET `avatar`=REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(`avatar`,'https://aldea.work/wp-content/uploads/','/img/wp/'),'https://www.aldea.work/wp-content/uploads/','/img/wp/'),'http://aldea.work/wp-content/uploads/','/img/wp/'),'http://www.aldea.work/wp-content/uploads/','/img/wp/'),'https:\\/\\/aldea.work\\/wp-content\\/uploads\\/','\\/img\\/wp\\/'),'https:\\/\\/www.aldea.work\\/wp-content\\/uploads\\/','\\/img\\/wp\\/') WHERE `avatar` LIKE '%wp-content%';
UPDATE `testimonials` SET `company_logo`=REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(`company_logo`,'https://aldea.work/wp-content/uploads/','/img/wp/'),'https://www.aldea.work/wp-content/uploads/','/img/wp/'),'http://aldea.work/wp-content/uploads/','/img/wp/'),'http://www.aldea.work/wp-content/uploads/','/img/wp/'),'https:\\/\\/aldea.work\\/wp-content\\/uploads\\/','\\/img\\/wp\\/'),'https:\\/\\/www.aldea.work\\/wp-content\\/uploads\\/','\\/img\\/wp\\/') WHERE `company_logo` LIKE '%wp-content%';

-- clients
UPDATE `clients` SET `logo`=REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(`logo`,'https://aldea.work/wp-content/uploads/','/img/wp/'),'https://www.aldea.work/wp-content/uploads/','/img/wp/'),'http://aldea.work/wp-content/uploads/','/img/wp/'),'http://www.aldea.work/wp-content/uploads/','/img/wp/'),'https:\\/\\/aldea.work\\/wp-content\\/uploads\\/','\\/img\\/wp\\/'),'https:\\/\\/www.aldea.work\\/wp-content\\/uploads\\/','\\/img\\/wp\\/') WHERE `logo` LIKE '%wp-content%';

-- blocks
UPDATE `blocks` SET `value_es`=REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(`value_es`,'https://aldea.work/wp-content/uploads/','/img/wp/'),'https://www.aldea.work/wp-content/uploads/','/img/wp/'),'http://aldea.work/wp-content/uploads/','/img/wp/'),'http://www.aldea.work/wp-content/uploads/','/img/wp/'),'https:\\/\\/aldea.work\\/wp-content\\/uploads\\/','\\/img\\/wp\\/'),'https:\\/\\/www.aldea.work\\/wp-content\\/uploads\\/','\\/img\\/wp\\/') WHERE `value_es` LIKE '%wp-content%';
UPDATE `blocks` SET `value_en`=REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(`value_en`,'https://aldea.work/wp-content/uploads/','/img/wp/'),'https://www.aldea.work/wp-content/uploads/','/img/wp/'),'http://aldea.work/wp-content/uploads/','/img/wp/'),'http://www.aldea.work/wp-content/uploads/','/img/wp/'),'https:\\/\\/aldea.work\\/wp-content\\/uploads\\/','\\/img\\/wp\\/'),'https:\\/\\/www.aldea.work\\/wp-content\\/uploads\\/','\\/img\\/wp\\/') WHERE `value_en` LIKE '%wp-content%';

