-- Opiniones en ingles. En /en/ (inicio y sedes) se veian en espanol: quote_en estaba vacio y en
-- las sedes el bloque en ingles tenia copiado el texto en espanol.
-- Solo cambia la opinion si el texto en espanol sigue igual y si el ingles esta vacio o es la copia
-- del espanol; si el cliente ya escribio su propia traduccion, se respeta.
SET NAMES utf8mb4;
UPDATE testimonials SET quote_en='We loved how well located Aldea is. Everything we need is close by, and that makes day-to-day life much easier.' WHERE name='Eitzel Galindo' AND (quote_en IS NULL OR quote_en='' OR quote_en=quote_es) AND quote_es='Nos encantó que Aldea estuviera tan bien ubicado. Tenemos todo cerca y eso hace la vida diaria mucho más práctica.';
UPDATE testimonials SET quote_en='Coming to work without having to think about coffee, cleaning or the printer is priceless. Everything is ready, and that gives us peace of mind.' WHERE name='Eduardo Velázquez' AND (quote_en IS NULL OR quote_en='' OR quote_en=quote_es) AND quote_es='Venir a trabajar sin pensar en el café, la limpieza o la impresora no tiene precio. Todo está listo y eso nos da paz mental.';
UPDATE testimonials SET quote_en='What we like most is how the team treats us. They sort things out quickly and with a great attitude. You can tell they care about helping you.' WHERE name='Enrique del Campo' AND (quote_en IS NULL OR quote_en='' OR quote_en=quote_es) AND quote_es='Lo que más nos gusta es el trato del equipo. Te resuelven rápido y con buena actitud. Se siente que les importa ayudarte.';
UPDATE testimonials SET quote_en='When we started, there were only three of us. Now we are six and still at Aldea. They have been very flexible and have supported us at every stage.' WHERE name='Miguel Barrientos' AND (quote_en IS NULL OR quote_en='' OR quote_en=quote_es) AND quote_es='Cuando empezamos éramos solo tres personas. Ahora somos seis y seguimos en Aldea. Han sido muy flexibles y nos han acompañado en cada etapa.';
UPDATE testimonials SET quote_en='We had very specific network requirements, and Aldea helped us set up our VPN without any trouble. Having a backup internet connection is reassuring.' WHERE name='Salvador Marín' AND (quote_en IS NULL OR quote_en='' OR quote_en=quote_es) AND quote_es='Teníamos requisitos muy específicos de red, y en Aldea nos apoyaron a configurar nuestra VPN sin problema. Contar con internet de respaldo nos da tranquilidad.';
UPDATE blocks SET value_en='We loved how well located Aldea is. Everything we need is close by, and that makes day-to-day life much easier.' WHERE page_id IN (SELECT id FROM pages WHERE slug LIKE 'loc:%') AND section='testi' AND skey LIKE 'q%' AND (value_en IS NULL OR value_en='' OR value_en=value_es) AND value_es='Nos encantó que Aldea estuviera tan bien ubicado. Tenemos todo cerca y eso hace la vida diaria mucho más práctica.';
UPDATE blocks SET value_en='Coming to work without having to think about coffee, cleaning or the printer is priceless. Everything is ready, and that gives us peace of mind.' WHERE page_id IN (SELECT id FROM pages WHERE slug LIKE 'loc:%') AND section='testi' AND skey LIKE 'q%' AND (value_en IS NULL OR value_en='' OR value_en=value_es) AND value_es='Venir a trabajar sin pensar en el café, la limpieza o la impresora no tiene precio. Todo está listo y eso nos da paz mental.';
UPDATE blocks SET value_en='What we like most is how the team treats us. They sort things out quickly and with a great attitude. You can tell they care about helping you.' WHERE page_id IN (SELECT id FROM pages WHERE slug LIKE 'loc:%') AND section='testi' AND skey LIKE 'q%' AND (value_en IS NULL OR value_en='' OR value_en=value_es) AND value_es='Lo que más nos gusta es el trato del equipo. Te resuelven rápido y con buena actitud. Se siente que les importa ayudarte.';
UPDATE blocks SET value_en='When we started, there were only three of us. Now we are six and still at Aldea. They have been very flexible and have supported us at every stage.' WHERE page_id IN (SELECT id FROM pages WHERE slug LIKE 'loc:%') AND section='testi' AND skey LIKE 'q%' AND (value_en IS NULL OR value_en='' OR value_en=value_es) AND value_es='Cuando empezamos éramos solo tres personas. Ahora somos seis y seguimos en Aldea. Han sido muy flexibles y nos han acompañado en cada etapa.';
UPDATE blocks SET value_en='We had very specific network requirements, and Aldea helped us set up our VPN without any trouble. Having a backup internet connection is reassuring.' WHERE page_id IN (SELECT id FROM pages WHERE slug LIKE 'loc:%') AND section='testi' AND skey LIKE 'q%' AND (value_en IS NULL OR value_en='' OR value_en=value_es) AND value_es='Teníamos requisitos muy específicos de red, y en Aldea nos apoyaron a configurar nuestra VPN sin problema. Contar con internet de respaldo nos da tranquilidad.';
